---
abstract: 'transform JSON using JsonT'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
keywords:
  - JSON
  - transform
  - JsonT
  - Javascript
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-T
no_index:
  directory:
    - inc
    - t
requires:
  JE: 0.049
  JSON: 2.00
  common::sense: 1.00
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-T
  homepage: http://search.cpan.org/dist/JSON-T/
  license: http://opensource.org/licenses/lgpl-license.php
  repository: http://goddamn.co.uk/viewvc/perlmods/JSON-T/
version: 0.090_04
