# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/JSON-T/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:recommends "JavaScript::SpiderMonkey" ;
	:requires "JSON" , "JE" , "Class::Load", "common::sense" , "Scalar::Util", "Object::AUTHORITY".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/JSON/T.pm" .

